services:
  frontend:
    image: awesome/webapp
    ports:
      - "8000:5000"

  monitoring:
    image: awesome/monitoring
    extends:
      service: frontend

  backend:
    image: awesome/backend
    extends:
      service: frontend
    ports:
      - "8000:5001"