services:
  frontend:
    image: awesome/webapp
    networks:
      - front-tier
      - back-tier
    depends_on:
      - monitoring
      - backend

  monitoring:
    image: awesome/monitoring
    networks:
      - admin

  backend:
    image: awesome/backend
    networks:
      back-tier:
        aliases:
          - database
      admin:
        aliases:
          - mysql

networks:
  front-tier:
  back-tier:
  admin: