services:
  frontend:
    image: awesome/webapp
    ports:
      - "8000:5000"

  monitoring:
    image: awesome/monitoring
    depends_on:
      - backend
    extends:
      service: frontend
    ports:
      - "8000:5010"

  backend:
    image: awesome/backend
    extends:
      service: frontend
    ports:
      - "8000:5001"