services:
  frontend:
    image: awesome/webapp

  monitoring:
    image: awesome/monitoring
    

  backend:
    image: awesome/backend
    extends:
      service: frontend
    ports:
      - "8000:5010"
    links:
      - "db:database"
  db:
    image: postgres
