services:
  frontend:
    image: awesome/webapp
    networks:
      - front-tier
      - back-tier

  monitoring:
    image: awesome/monitoring
    networks:
      - admin
    

  backend:
    image: awesome/backend
    networks:
      back-tier:
        aliases:
          - database
      admin:
        aliases:
          - mysql
    depends_on:
      - monitoring
    links:
      - "db:database"
  db:
    image: postgres

networks:
  front-tier:
  back-tier:
  admin: