services:
  frontend:
    image: awesome/webapp

  monitoring:
    image: awesome/monitoring
    depends_on:
      - backend
    volumes:
      - type: volume
        source: db-data
        target: /data
        volume:
          nocopy: true
      - type: bind
        source: /var/run/postgres/postgres.sock
        target: /var/run/postgres/postgres.sock
    links:
      - "db:database"

  backend:
    image: awesome/backend
  db:
    image: postgres
volumes:
  db-data: