# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}
              
      - name: Set up Python 3.10.4
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.4
      - name: Docker Compose Config
        run: |
          docker-compose -f testfiles/000001.yaml config -q
          docker-compose -f testfiles/000010.yaml config -q
          docker-compose -f testfiles/000011.yaml config -q
          docker-compose -f testfiles/000100.yaml config -q
          docker-compose -f testfiles/000101.yaml config -q
          docker-compose -f testfiles/000110.yaml config -q
          docker-compose -f testfiles/000111.yaml config -q
          docker-compose -f testfiles/001000.yaml config -q
          docker-compose -f testfiles/001001.yaml config -q
          docker-compose -f testfiles/001010.yaml config -q
          docker-compose -f testfiles/001011.yaml config -q
          docker-compose -f testfiles/001100.yaml config -q
          docker-compose -f testfiles/001101.yaml config -q
          docker-compose -f testfiles/001110.yaml config -q
          docker-compose -f testfiles/001111.yaml config -q
          docker-compose -f testfiles/010000.yaml config -q
          docker-compose -f testfiles/010001.yaml config -q
          docker-compose -f testfiles/010010.yaml config -q
          docker-compose -f testfiles/010011.yaml config -q
          docker-compose -f testfiles/010100.yaml config -q
          docker-compose -f testfiles/010101.yaml config -q
          docker-compose -f testfiles/010110.yaml config -q
          docker-compose -f testfiles/010111.yaml config -q
          docker-compose -f testfiles/011000.yaml config -q
          docker-compose -f testfiles/011001.yaml config -q
          docker-compose -f testfiles/011010.yaml config -q
          docker-compose -f testfiles/011011.yaml config -q
          docker-compose -f testfiles/011100.yaml config -q
          docker-compose -f testfiles/011101.yaml config -q
          docker-compose -f testfiles/011110.yaml config -q
          docker-compose -f testfiles/011111.yaml config -q
          docker-compose -f testfiles/100000.yaml config -q
          docker-compose -f testfiles/100001.yaml config -q
          docker-compose -f testfiles/100010.yaml config -q
          docker-compose -f testfiles/100011.yaml config -q
          docker-compose -f testfiles/100100.yaml config -q
          docker-compose -f testfiles/100101.yaml config -q
          docker-compose -f testfiles/100110.yaml config -q
          docker-compose -f testfiles/100111.yaml config -q
          docker-compose -f testfiles/101000.yaml config -q
          docker-compose -f testfiles/101001.yaml config -q
          docker-compose -f testfiles/101010.yaml config -q
          docker-compose -f testfiles/101011.yaml config -q
          docker-compose -f testfiles/101100.yaml config -q
          docker-compose -f testfiles/101101.yaml config -q
          docker-compose -f testfiles/101110.yaml config -q
          docker-compose -f testfiles/101111.yaml config -q
          docker-compose -f testfiles/110000.yaml config -q
          docker-compose -f testfiles/110001.yaml config -q
          docker-compose -f testfiles/110010.yaml config -q
          docker-compose -f testfiles/110011.yaml config -q
          docker-compose -f testfiles/110100.yaml config -q
          docker-compose -f testfiles/110101.yaml config -q
          docker-compose -f testfiles/110110.yaml config -q
          docker-compose -f testfiles/110111.yaml config -q
          docker-compose -f testfiles/111000.yaml config -q
          docker-compose -f testfiles/111001.yaml config -q
          docker-compose -f testfiles/111010.yaml config -q
          docker-compose -f testfiles/111011.yaml config -q
          docker-compose -f testfiles/111100.yaml config -q
          docker-compose -f testfiles/111101.yaml config -q
          docker-compose -f testfiles/111110.yaml config -q
          docker-compose -f testfiles/111111.yaml config -q
            
      - name: User Input Test with Config
        #working-directory: src/
        run: |
          pip install pytest
          pip install pytest-cov
          python -m pytest src/test.py testfiles/docker-compose.yaml
        # python3 compose-viz.py testfiles/docker-compose.yaml
        # pytest src/test.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html   
          
      #- name: Install dependencies
       # run: |
          #pip install -r requirements.txt
          
          #pip install -e .
